- name: This playbook install, cofigure and deploy web pages into nginx
  hosts: appservers
  become: yes
  vars:
    - course_name: DevOps with Ansible, XLR & Docker
  tasks:
    - name: Install nginx web server in Ubuntu
      apt: name=nginx state=latest update_cache=yes
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )

    - name: Install Extra packages for Enterprise Linux in CentOS
      yum: name=epel-release state=latest
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

    - name: Enable baseurl and disable mirror link in the epel repos under CentOS
      copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

    - name: Install nginx web server in CentOS
      yum: name=nginx state=latest
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

    - name: Create nginx web root folder
      file: path=/var/html mode=0777 state=directory

    - name: Configure nginx web root folder in Ubuntu
      copy: src=default dest=/etc/nginx/sites-available/default
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )

    - name: Configure nginx web root folder in CentOS
      copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

    
    - name: Deploy custom webpage into nginx web server on container
      template: src=index.html.j2 dest=/var/html/index.html

    - name: Restart nginx Server
      #service: name=nginx state=started enabled=yes
      command: service nginx restart
      
